#include "cpu.hpp"
#include "gameboy.hpp"

static void nop(Gameboy&)
{

}

static void stop(Gameboy& gb)
{
	
}

static void rlca(Gameboy& gb)
{
	
}

static void ld_bc_nn(Gameboy& gb, uint16_t value)
{
	gb.registers.bc() = value;
}

#define EACH_R(M, ...) M(a, __VA_ARGS__) M(b, __VA_ARGS__) M(c, __VA_ARGS__) M(d, __VA_ARGS__) M(e, __VA_ARGS__) M(h, __VA_ARGS__) M(l, __VA_ARGS__)
#define EACH_RR(M) M(af) M(bc) M(de) M(hl)

#define LD_DRR_R(r1, r2) static void ld_##r1##_##r2##(Gameboy& gb) { gb.mmu.memMap[gb.registers.##r1##()] = gb.registers.##r2; }
LD_DRR_R(bc, a)

#define LD_R_DRR(r1, r2) static void ld_##r1##_##r2##(Gameboy& gb) { gb.registers.##r1 = gb.mmu.memMap[gb.registers.##r2##()]; }
LD_R_DRR(a, bc)
LD_R_DRR(a, de)

#define LD_RR(r1, r2) static void ld_##r1##_##r2(Gameboy& gb) { gb.registers.##r1 = gb.registers.##r2; }
LD_RR(a, b)
LD_RR(b, a)
LD_RR(c, a)
LD_RR(b, c)
LD_RR(c, b)
LD_RR(d, a)
LD_RR(a, d)
LD_RR(d, b)

#define LD_RN(r) static void ld_##r##_n(Gameboy& gb, uint8_t value) { gb.registers.##r = value; }
EACH_R(LD_RN)

#define INC_R(r) static void inc_##r(Gameboy& gb) { gb.registers.##r++; }
EACH_R(INC_R)
INC_R(sp)

#define DEC_R(r) static void dec_##r(Gameboy& gb) { gb.registers.##r--; }
EACH_R(DEC_R)
DEC_R(sp)

#define INC_RR(r) static void inc_##r(Gameboy& gb) { gb.registers.##r()++; }
EACH_RR(INC_RR)

#define DEC_RR(r) static void dec_##r(Gameboy& gb) { gb.registers.##r()--; }
EACH_RR(DEC_RR)

#define BIN_OP(r, opname, op) static void opname##_##r(Gameboy& gb) { gb.registers.a op gb.registers.##r; }
// for some reason this doesn't compiles on MSVC
//EACH_R(BIN_OP, add, +=)

#define ADD_R(r) static void add_##r(Gameboy& gb) { gb.registers.a += gb.registers.##r; }
EACH_R(ADD_R)

#define SUB_R(r) static void sub_##r(Gameboy& gb) { gb.registers.a -= gb.registers.##r; }
EACH_R(SUB_R)

static void add_n(Gameboy& gb, uint8_t value)
{
	gb.registers.a += value;
}

static void sub_n(Gameboy& gb, uint8_t value)
{
	gb.registers.a -= value;
}

#define XOR_R(r) static void xor_##r(Gameboy& gb) { gb.registers.a ^= gb.registers.##r; }
EACH_R(XOR_R)

static void xor_n(Gameboy& gb, uint8_t value)
{
	gb.registers.a ^= value;
}

#define AND_R(r) static void and_##r(Gameboy& gb) { gb.registers.a &= gb.registers.##r; }
EACH_R(AND_R)

static void and_n(Gameboy& gb, uint8_t value)
{
	gb.registers.a &= value;
}

#define OR_R(r) static void or_##r(Gameboy& gb) { gb.registers.a |= gb.registers.##r; }
EACH_R(OR_R)

static void or_n(Gameboy& gb, uint8_t value)
{
	gb.registers.a |= value;
}


#define UNDEFINED_INSTRUCTION {0, 0, nop, "UNDEFINED"}

Instruction instructions[256] = {
	{ 1, 4, nop, "NOP"},
	{ 3, 6, ld_bc_nn, "LD BC, 0x%04X" },
	{ 1, 8, ld_bc_a, "LD (BC), A" },
	{ 1, 8, inc_bc, "INC BC" }, // 03
	{ 1, 4, inc_b, "INC B" }, // 04
	{ 1, 4, dec_b, "DEC B" },
	{ 2, 4, ld_b_n, "LD B, 0x%02X" },
	{ 1, 4, rlca, "RLCA" },
	UNDEFINED_INSTRUCTION,
	{ 1, 8, ld_a_bc, "LD A,(BC)" }, // 0A
	{ 1, 8, dec_bc, "DEC BC" }, //0B
	{ 1, 4, inc_c, "INC C" }, //0C
	{ 1, 4, dec_c, "DEC C" }, // 0D
	UNDEFINED_INSTRUCTION, // 0E
	UNDEFINED_INSTRUCTION, // 0F
	{1, 0, stop, "STOP"}, // 10
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	{ 1, 4, inc_d, "INC D" }, // 14
	{ 1, 4, dec_d, "DEC D" },
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	{ 1, 8, ld_a_de, "LD A,(DE)" }, // 1A
	{ 1, 8, dec_de, "DEC DE" },
	{ 1, 4, inc_e, "INC E" },
	{ 1, 4, dec_e, "DEC E" }, // 1D
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION, // 1F
	UNDEFINED_INSTRUCTION, // 20
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	{ 1, 8, inc_hl, "INC HL" }, // 23
	{ 1, 4, inc_h, "INC H" },
	{ 1, 4, dec_h, "DEC H" },
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	{ 1, 8, dec_hl, "DEC HL" }, // 2B
	{ 1, 4, inc_l, "INC L" },
	{ 1, 4, dec_l, "DEC L" },
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION, // 30
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	{ 1, 8, inc_sp, "INC SP" }, // 33
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	{ 1, 8, dec_sp, "DEC SP" }, // 3B
	{ 1, 4, inc_a, "INC A" },
	{ 1, 4, dec_a, "DEC A" }, // 3D
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION, // 40
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
	UNDEFINED_INSTRUCTION,
};
